### ISSUE TITLE
پینگ ندادن

### ISSUE THREAD

**Issue by Pezhman5252** [idaniali/6to4-tunnel-IPV6-Local#10]
تمام مراحل رو دقیق مطابق آموزش انجام دادم ولی پینگ ندارم از سرور ها، از ایران به خارج و بلعکس، نه ip6 و نه ip لوکال. دلیلش چیه؟

**Comment by idaniali** [comment]
امکانش هست دیتاسنترتون پروتکل ۴۱ رو بسته باشه .
