### ISSUE TITLE
خطا در ست کردن روی ایران

### ISSUE THREAD

**Issue by biggod01** [idaniali/6to4-tunnel-IPV6-Local#11]
موقع ست کردن ایپی داخل سرور ایران این خطا رو میده به نظرتون چجوری حل کنم؟
Error: inet6 prefix is expected rather than "f9f:4eb9:65c:z::asc1/64"

**Comment by idaniali** [comment]
قوانین ipv6 و هتزادسیمال رو مطالعه بفرمایید ...
