### ISSUE TITLE
ارور : add tunnel "sit0" failed: No buffer space available

### ISSUE THREAD

**Issue by hosseini2024** [idaniali/6to4-tunnel-IPV6-Local#12]
سلام
اول تشکر می کنم بابت زحمت شما 

من بار اول تست کردم ولی تا مرحله سیو نرفتم و سرور ها رو ریبوت زدم ، خواستم دوباره مراحل برم این ارور رو داد :

add tunnel "sit0" failed: No buffer space available

 سعی کردم بعضی مقادیر رو تغییر بدم بلکه اوکی بشه اما نشد

ممنون میشم راهنمای کنید مشکل از کجاست

**Comment by idaniali** [comment]
تانل رو سرورتون فعال شده و داره اعلام میکنه که sit0 وجود داره و مجدد نمیتونه بسازتش . اخر داکیومنت حذف تانل رو گذاشتم . یک دو حذف کنید و از اول انجام بدید

**Comment by hosseini2024** [comment]
همین کار انجام دادم منتها تاتل از رو سروز ایرانوماک میشه ولی از رو سرور خارج پاک نمیشه و همون ارور موقع وارد وردن دستور میده

Sent from Yahoo Mail on Android 
 
  On سه‌شنبه, ژوئن ۴, ۲۰۲۴ at ۲۳:۴۴, ***@***.***> wrote:   


Closed #12 as completed.

**Comment by hosseini2024** [comment]
بعد از دستور پاکسازی مجدد دستور راه اندازی تانل وارد کردم و همون ارور ها رو دریافت کردم
راه دیگه ای برای پاک کردن تانل وجود نداره ؟ 
Sent from Yahoo Mail on Android 
 
  On سه‌شنبه, ژوئن ۴, ۲۰۲۴ at ۲۳:۴۴, ***@***.***> wrote:   


تانل رو سرورتون فعال شده و داره اعلام میکنه که sit0 وجود داره و مجدد نمیتونه بسازتش . اخر داکیومنت حذف تانل رو گذاشتم . یک دو حذف کنید و از اول انجام بدید
