### ISSUE TITLE
سوال

### ISSUE THREAD

**Issue by hosseini2024** [idaniali/6to4-tunnel-IPV6-Local#14]
با سلام
وقت بخیر

اول تشکر میکنم بابت تانل خوبی که معرفی کردید

سوالم اینه که چرا بعد از نصب تانل پنلی که رو سرور ایران هست دیگه بالا نمیاد ؟
آیا دلیل خاصی داره و میشه رفعش کرد ؟

و اینکه چطور میشه با این روش دوتا خارج به یک ایران تانل زد ، ممنون میشم راهنمایی کنید

**Comment by idaniali** [comment]
با دستوری که در اخر سر وارد میکنید ، تمامی ترافیک ها به جز پورت 22 به سمت سرور خارج فوروارد میشه به همین دلیل اگر پنلی روی ایران دارید باز نمیشه
