### ISSUE TITLE
پینگ لوکال

### ISSUE THREAD

**Issue by omid1381a** [idaniali/6to4-tunnel-IPV6-Local#15]
با سلام من اختصاصی آسیاتک داشتم 
با این روش تانل میکردم ولی از امروز عصر روی سرور های اختصاصیش پینگ لوکال نمیشه گرفت داخل سرور 
مثلا توی سرور ایران میخوام پینگ لوکال خارج رو بگیرم پینگ نمیده 
ولی توی اشتراکی های آسیا یا آروان جواب میده باز مشکل از چی میتونه باشه ممنون میشم راهنمایی کنید.

**Comment by omid1381a** [comment]
از سرور خارج هم نمیشه پینگ لوکال ایران رو گرفت

**Comment by idaniali** [comment]
مشکلات متعددی میتونه باشه ، ایپی های v6 و v4 لوکال رو تغییر بدید ، mtu رو تغییر بدید ، هر دو سرور ها رو ریبیلد کنید و در اخر اگر نتیجه نگرفتید ایپی خارج رو تغییر بدید
