### ISSUE TITLE
ارتباط بین Ubuntu و CentOS

### ISSUE THREAD

**Issue by AerEbi** [idaniali/6to4-tunnel-IPV6-Local#16]
سلام وقت بخیر
ممنون از آموزش خوب‌تون

یه مشکلی که هست اینکه گاهی ارتباط با آی‌پی6 لوکال قطع می‌شه و باید تو هر دو سرور پینگ آی‌پی لوکال رو بزنیم تا دوباره ارتباط برقرار شهو
راهی هست که بشه این مشکل رو حل کرد تا مجبور نباشم مدام دستور پینگ + آی‌پی رو توی سرور بزنم؟
اینم بگم که یه سرور ubuntu و یکی دیگه centos هست.

ممنون می‌شم راهنمایی کنید.

**Comment by idaniali** [comment]
روی سرور خارج این دستور رو اعمال کنید : 
nohup ping <IPv4-local-Iran> &
جای <IPv4-local-Iran> ایپی لوکال v4 ایران رو قرار بدید و در سرور خارج واردش کنید .
