### ISSUE TITLE
ترافیک مصرفی

### ISSUE THREAD

**Issue by biggod01** [idaniali/6to4-tunnel-IPV6-Local#18]
سلام وقت شما بخیر
ایا لوکال باعث میشه ترافیک یورز ها بیشتر بشه
یعنی زودتر به اتمام برسه؟

**Comment by idaniali** [comment]
خیر روی یوزر ها تاثیری نداره ولی تانلتون بین 15 تا 20 درصد بیشتر از چیزی که یوزر ها مصرف میکنن ، مصرف میشه .
