### ISSUE TITLE
multi server

### ISSUE THREAD

**Issue by PwnWorld** [idaniali/6to4-tunnel-IPV6-Local#19]
برای چند سرور خارج باید چکار کرد

**Comment by idaniali** [comment]
برای اینکه تانل رو به چند سرور خارج وصل کنید چندین حالت داره : 
1 ) پنل روی سرور ایران باشه 
2) پنل روی سرور خارج باشه 

اگر مورد 1 هست باید از لود بالانس استفاده کنید که توضیح دادنش در اینجا نمیگنجه 

اگر هم مورد 2 هست با تفکیک پورت میتونید به چند تا خارج تانل بزنید ولی به شرطی که بین پنل ها پورت مشترکی وجود نداشته باشه
