### ISSUE TITLE
فوروارد کردن ترافیک سرور ایران

### ISSUE THREAD

**Issue by sadegh1210** [idaniali/6to4-tunnel-IPV6-Local#2]
با سلام و خسته نباشید
همه این کارا رو ما تو میکروتیک انجام میدیم و با این مقوله اشنام.
الان اینارو هم زدم رو لینوکس ولی من فقط سوالم اینه که نمیخوام ترافیک ایران رو با ip table فوروارد کنم ، چون کاربرا رو سرور ایرانن و باید outbond رو تنظیم کرد.
ممنون میشوم تو لینوکس این مورد رو راهنایی کنید.

**Comment by Saeedroshan1906** [comment]
از اسکریپت گلست ورژن ۳ استفاده کنید و اون ایپی ۶ لوکال و قرار بدید یا از دکودومودور

**Comment by sadegh1210** [comment]
برای اینکه از دکو استفاده کنم حتما باید سرور مقصدم هم v2ray بالا اورده باشم یا نه ؟
