### ISSUE TITLE
عدم برقراری تانل

### ISSUE THREAD

**Issue by mansourarshia** [idaniali/6to4-tunnel-IPV6-Local#21]
سلام و خسته نباشید. 

بنده چند ماه از این تانل استفاده کردم و هیچ مشکلی نداشتم اما جدیدا به دلیلی که متوجهش نمیشم اصلا موفق نمیشم تانل رو برقرار کنم. 
توی همون مرحله اول که دوتا دستور رو برای اضافه کردن آی پی لوکال میزنم گیر میکنم چون سرور ها از هم پینگ نمیگیرن و به عبارتی اتصال برقرار نیست. 

سرور هارو تعویض کردم، مقدار MTU رو تغییر دادم، با آی پی های رندوم زیادی تست کردم و آی پی که در مثال به کار برده شده روهم امتحان کردم اما نتیجه نگرفتم. ممنون میشم کمکم کنید.

![Screenshot 2024-09-07 090134](https://github.com/user-attachments/assets/60473a55-97c4-4528-ae65-67e1e5d5beca)
![Screenshot 2024-09-07 090148](https://github.com/user-attachments/assets/07a6c8e7-de23-4bdd-bd57-077e4a4461a7)

**Comment by idaniali** [comment]
سلام . امکانش هست از سمت دیتاسنتر ایران ، پروتکل 6to4 رو مسدود کرده باشن ، گاهی وقتا با ریبیلد کردن سرور ایران و خارج مشکل حل میشه.

**Comment by mansourarshia** [comment]
ممنونم. ریبیلد روهم امتحان میکنم. آیا جایگزین مناسبی میشناسید که اینقدر تر و تمیز کار کنه؟

**Comment by idaniali** [comment]
روی میکروتیک مانور بیشتری میتونید بدید ....

**Comment by mansourarshia** [comment]
درودی دوباره، عزیز متوجه شدم که سایتی که سرور خارجی ازش تهیه میکنم (doprax) باعث میشه که اتصال برقرار نشه. ازش سرور های دیتاسنتر هتزنر میگیرم. میشه برای اینکه این مشکل حل شه کاری کرد؟
