### ISSUE TITLE
ufw 

### ISSUE THREAD

**Issue by sadegh1210** [idaniali/6to4-tunnel-IPV6-Local#3]
با سلام
موقعی که ufw داخل سرور خارج روشن میشه ارتباط gre قطع میشه ولی ارتباط 6to4 برقراره.
با وجود اینکه آیپی سرور ایران رو تو whitelist سرور خارج گذاشتم ولی تانل gre برقرار نمیشه.

**Comment by idaniali** [comment]
برای فایروال ترجیها از خوده دیتاسنتر استفاده کنید . و اینکه برا ufw رنجه v6 لوکالی که ست کردید رو هم باز کنید .
