### ISSUE TITLE
مولتی تانل

### ISSUE THREAD

**Issue by Saeedroshan1906** [idaniali/6to4-tunnel-IPV6-Local#4]
برای اینکه یک سرور خارج به دوتا ایران متصل بشه باید چیکار کرد ؟

**Comment by idaniali** [comment]
قسمت هایی که bold کردم رو باید تغییر بدید تا با تانل قبلی تداخل نداشته باشه :
1- اسم تانل ها
2- ایپی های لوکالی که ساخته میشه (جوری تغییر بدید که ایپی های جدید در رنج همدیگر باشن )


ip tunnel add **6to4_To_KH** mode sit remote IPv4-Kharej local IPv4-Iran
ip -6 addr add **fc00::1/64** dev **6to4_To_KH**
ip link set 6to4_To_KH mtu 1480
ip link set 6to4_To_KH up

ip -6 tunnel add **ipip6Tun_To_KH** mode ipip6 remote **fc00::2** local **fc00::1**
ip addr add **192.168.13.1/30** dev **ipip6Tun_To_KH**
ip link set **ipip6Tun_To_KH** mtu 1440
ip link set **ipip6Tun_To_KH** up

**Comment by Saeedroshan1906** [comment]
ممنونم
