### ISSUE TITLE
کار کردن تانل روی سرور فیلتر

### ISSUE THREAD

**Issue by hayousef68** [idaniali/6to4-tunnel-IPV6-Local#5]
سلام.داداش آیا این روش روی سرور فیلتر خارج هم جواب میده؟؟؟
و اینکه مثل آی پی فروارد زود بسته میشه یا فرق داره با اون؟؟؟

**Comment by radG1t** [comment]
رو سرور خارج فیلتر جواب میده.

**Comment by hayousef68** [comment]
> رو سرور خارج فیلتر جواب میده.


ممنون داداش . معمولا آی پی لوکال ترافیک مصرف بیشتری داره نسبت به بقیه تانل ها
برا این روش هم اینطوریه یا نه؟؟؟

**Comment by idaniali** [comment]
> ممنون داداش . معمولا آی پی لوکال ترافیک مصرف بیشتری داره نسبت به بقیه تانل ها برا این روش هم اینطوریه یا نه؟؟؟


مقدار خیلی جزئی مصرف بیشتر هستش ولی اونقدری نیست که به چشم بیاد
