### ISSUE TITLE
مصرف نامتقارن پنل

### ISSUE THREAD

**Issue by sadegh1210** [idaniali/6to4-tunnel-IPV6-Local#6]
با سلام
بعد ازاینکه این تانل رو زدم بعد از چند روز ترافیک مصرفی پنل متقارن نیست.
به خاطر این نوع تانلست ؟
![Screenshot 2024-05-04 113235](https://github.com/idaniali/6to4-tunnel-IPV6-Local/assets/133211419/94e4b49f-519c-4cea-ad68-fe60f0e7e787)

**Comment by idaniali** [comment]
باگ پنل های xui هست . به صورت نرمال باید فقط مصرفه ether1 محاسبه بشه ولی این پنل ها تانل رو هم محاسبه میکنند  .

**Comment by sadegh1210** [comment]
خب با این حال
مصرف ترافیک هم زیاد میشه یا نه ؟
