### ISSUE TITLE
فرق IPIPv6 و GRE6

### ISSUE THREAD

**Issue by omid1381a** [idaniali/6to4-tunnel-IPV6-Local#7]
با سلام و وقت بخیر
ببخشید میخواستم فرق تانل IPIPv6 و GRE6 بدونم مخصوصا این که از نظر سرعت و امنیت کدوم یکی بهتره
مخصوصا امنیت که آیپی خارج رو مسدود نکنن
ممنون میشم راهنمایی کنید متشکرم.

**Comment by idaniali** [comment]
سلام 
تانل 6to4 رو ایپی فیلتر هم کار میکنه . روی بعضی از دیتاسنتر ها ipipv6 رو بستن همون gre6 رو بزنید .

**Comment by omid1381a** [comment]
از لحاظ سرعت با هم فرق زیادی دارن یا نه تقریبا یکی هستن؟
