### ISSUE TITLE
دریافت پیغام خطا در نصب روی سرور خارج

### ISSUE THREAD

**Issue by mohsenneikan** [idaniali/6to4-tunnel-IPV6-Local#8]
add tunnel "sit0" failed: No buffer space available
Cannot find device "6to4_To_IR"
Cannot find device "6to4_To_IR"
Cannot find device "6to4_To_IR"

**Comment by idaniali** [comment]
وقتی یک دور تانل رو وارد میکنید ، چه کامل دستورات رو وارد کنید چه ناقص ، یا اینکه قسمتی از تانل رو اشتباه بزنید ، تانل ساخته میشه . در اینجا یک دو دستورات رو وارد کردید و میخواید مجدد وارد کنید و داره اعلام میکنه sit0 وجود داره . یا باید تانل رو پاک کنید یا اینکه سرور رو ریبوت کنید .
